[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"
authors = ["Yomogi"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello_world = { path = "hello_world" }