[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
authors = ["Yomogi"]

[lib]
path = "src/hello_world.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]